from pycocotools.coco import COCO
import numpy as np
from vlm_api import chat_image
from tqdm import tqdm
from PIL import Image
import os
import re
import utils

categories = {
    1: 'wall',
    2: 'building',
    3: 'sky',
    4: 'floor',
    5: 'tree',
    6: 'ceiling',
    7: 'road',
    8: 'bed',
    9: 'windowpane',
    10: 'grass',
    11: 'cabinet',
    12: 'sidewalk',
    13: 'person',
    14: 'earth',
    15: 'door',
    16: 'table',
    17: 'mountain',
    18: 'plant',
    19: 'curtain',
    20: 'chair',
    21: 'car',
    22: 'water',
    23: 'painting',
    24: 'sofa',
    25: 'shelf',
    26: 'house',
    27: 'sea',
    28: 'mirror',
    29: 'rug',
    30: 'field',
    31: 'armchair',
    32: 'seat',
    33: 'fence',
    34: 'desk',
    35: 'rock',
    36: 'wardrobe',
    37: 'lamp',
    38: 'bathtub',
    39: 'railing',
    40: 'cushion',
    41: 'base',
    42: 'box',
    43: 'column',
    44: 'signboard',
    45: 'chest',
    46: 'counter',
    47: 'sand',
    48: 'sink',
    49: 'skyscraper',
    50: 'fireplace',
    51: 'refrigerator',
    52: 'grandstand',
    53: 'path',
    54: 'stairs',
    55: 'runway',
    56: 'case',
    57: 'pool',
    58: 'pillow',
    59: 'screen',
    60: 'stairway',
    61: 'river',
    62: 'bridge',
    63: 'bookcase',
    64: 'blind',
    65: 'coffee',
    66: 'toilet',
    67: 'flower',
    68: 'book',
    69: 'hill',
    70: 'bench',
    71: 'countertop',
    72: 'stove',
    73: 'palm',
    74: 'kitchen',
    75: 'computer',
    76: 'swivel',
    77: 'boat',
    78: 'bar',
    79: 'arcade',
    80: 'hovel',
    81: 'bus',
    82: 'towel',
    83: 'light',
    84: 'truck',
    85: 'tower',
    86: 'chandelier',
    87: 'awning',
    88: 'streetlight',
    89: 'booth',
    90: 'television',
    91: 'airplane',
    92: 'dirt',
    93: 'apparel',
    94: 'pole',
    95: 'land',
    96: 'bannister',
    97: 'escalator',
    98: 'ottoman',
    99: 'bottle',
    100: 'buffet',
    101: 'poster',
    102: 'stage',
    103: 'van',
    104: 'ship',
    105: 'fountain',
    106: 'conveyer',
    107: 'canopy',
    108: 'washer',
    109: 'plaything',
    110: 'swimming',
    111: 'stool',
    112: 'barrel',
    113: 'basket',
    114: 'waterfall',
    115: 'tent',
    116: 'bag',
    117: 'minibike',
    118: 'cradle',
    119: 'oven',
    120: 'ball',
    121: 'food',
    122: 'step',
    123: 'tank',
    124: 'trade',
    125: 'microwave',
    126: 'pot',
    127: 'animal',
    128: 'bicycle',
    129: 'lake',
    130: 'dishwasher',
    131: 'screen',
    132: 'blanket',
    133: 'sculpture',
    134: 'hood',
    135: 'sconce',
    136: 'vase',
    137: 'traffic',
    138: 'tray',
    139: 'ashcan',
    140: 'fan',
    141: 'pier',
    142: 'crt',
    143: 'plate',
    144: 'monitor',
    145: 'bulletin',
    146: 'shower',
    147: 'radiator',
    148: 'glass',
    149: 'clock',
    150: 'flag'
}

data_name = "ade20k_gemma_train"
img_path = "your_root_to_img"
ann_path = "your_root_to_ann"
for i,img in tqdm(enumerate(os.listdir(img_path)),total=len(os.listdir(img_path))):
    ai_ans = chat_image(os.path.join(img_path,img),categories)
    pred_ids = list(map(int, re.findall(r'\d+', ai_ans)))
    if pred_ids and max(pred_ids)>150:
        continue
    ann_img_path = os.path.join(ann_path,f"{img.split('.')[0]}.png")
    image = Image.open(ann_img_path).convert('L')
    pixel_values = np.array(image)
    gt_ids = np.unique(pixel_values)
    gt_ids = gt_ids[gt_ids != 0]
    gt_ids = gt_ids.tolist()
    utils.json_write(data_name, img, ai_ans, pred_ids, gt_ids)
    preds_label = np.zeros(151,dtype=int)
    preds_label[pred_ids] = 1
    gt_label = np.zeros(151,dtype=int)
    gt_label[gt_ids] = 1